export default<configGroup> {
  name: 'Y轴设置',
  configs: [{
    fieldType: 'color',
    fieldName: 'Y轴颜色',
    fieldCode: 'yAxisLineColor',
    defaultValue: '#999999',
  }, {
    fieldType: 'number',
    fieldName: '旋转角度',
    fieldCode: 'yAxisLabelRotate',
    defaultValue: 0,
  }, {
    fieldType: 'number',
    fieldName: '间隔',
    fieldCode: 'yAxisLabelInterval',
    defaultValue: 0,
  }, {
    fieldType: 'number',
    fieldName: '文字大小',
    fieldCode: 'yAxisLabelFontSize',
    defaultValue: 12,
  }, {
    fieldType: 'color',
    fieldName: '字体颜色',
    fieldCode: 'yAxisLabelFontColor',
    defaultValue: '#999999',
  }, {
    fieldType: 'switch',
    fieldName: '显示分割线',
    fieldCode: 'ySplitLineShow',
    defaultValue: true,
  }, {
    fieldType: 'color',
    fieldName: '分割线',
    fieldCode: 'ySplitLineColor',
    defaultValue: '#cccccc',
  }]
}